services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    init: true
    environment:
      TZ: Asia/Tokyo
      CHOKIDAR_USEPOLLING: 1
      HOST: 0.0.0.0
    ports:
      - "9502:9502"
    working_dir: /app/
    volumes:
      - ./:/app/
